version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements-test.txt
          pkg-manager: pip
      - python/install-packages:
          args: .
          pkg-manager: pip
      - run:
          command: pytest

workflows:
  main:
    jobs:
      - build-and-test
